# _config.yml
title: "Syed Saiful Arefin"
logo: /asserts/img/headshot_circle.png
#description: "Showcasing AI Projects and Skills"
#author: "Syed Saiful Arefin"
#email: "saiful.arefin786@gmail.com"
#github_username: "syedsaifularefin"

# Theme settings
theme: jekyll-theme-minimal

