# _config.yml
title: "Syed Saiful Arefin"
logo: /asserts/img/headshot_circle.png
#description: "Showcasing AI Projects and Skills"
#author: "Syed Saiful Arefin"
#email: "saiful.arefin786@gmail.com"
#github_username: "syedsaifularefin"

# Theme settings
theme: jekyll-theme-minimal


# Navigation Links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Contact"
    url: "/contact/"

# Social Links
social_links:
  github: "https://github.com/syedsaifularefin"
  linkedin: "https://www.linkedin.com/in/syed-saiful-arefin/"


